trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Docker@2
    displayName: "Build and push React Docker image to ACR"
    inputs:
      containerRegistry: "React-NodeJS"
      repository: "https://github.com/cubastion-training/sample-react-app.git"
      command: "buildAndPush"
      Dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
      tags: |
        $(Build.BuildId)
