trigger:
  branches:
    include:
      - master

stages:
  - stage: BuildReactApp
    displayName: Build and Push React App Docker Image
    jobs:
      - job: BuildReact
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: 'Build and push React Docker image'
            inputs:
              containerRegistry: 'React-NodeJS'  # Ensure this matches the service connection name
              repository: 'cubastion-training/sample-react-app'  # Updated GitHub repository path for the React app
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to Dockerfile for React app (assuming it's in the root)
              tags: |
                $(Build.BuildId)

  - stage: BuildNodeApp
    displayName: Build and Push Node.js App Docker Image
    jobs:
      - job: BuildNode
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: 'Build and push Node.js Docker image'
            inputs:
              containerRegistry: 'React-NodeJS'  # Ensure this matches the service connection name
              repository: 'cubastion-training/sample-node-app'  # Updated GitHub repository path for the Node.js app
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to Dockerfile for Node.js app (assuming it's in the root)
              tags: |
                $(Build.BuildId)
